---
- name: enable or disable node_exporter
  systemd:
    name: node_exporter@{{ local_port }}
    state: "{{ 'restarted' if update_status else 'stopped' }}"
    enabled: "{{ 'yes' if update_status else 'no' }}"
    daemon_reload: yes

- name: Check node_exporter service
  when: update_status
  block:
    - name: Get systemd status
      command: systemctl status node_exporter@{{ local_port }}
      register: systemd_status
      failed_when: "'Active: active' not in systemd_status.stdout"
  rescue:
    - name: Set node_exporter not exist
      when: "'/usr/local/bin/node_exporter: No such file or directory' in systemd_status.stdout"
      set_fact:
        node_exporter: ""
        cacheable: yes
    - name: Set error
      set_fact:
        error: "{{ systemd_status.stdout }}"
        cacheable: yes
    - name: Fail
      fail:
