---
- name: Check ehco exist
  block:
    - name: Get ehco version
      shell: ehco -v
      register: ehco
    - name: Set fact for ehco version
      set_fact:
        ehco: "{{ ehco.stdout }}"
        cacheable: yes
  rescue:
    - name: Set ehco not exist
      set_fact:
        ehco: ""
        cacheable: yes
