---
- name: Check ehco exist
  block:
    - name: Check ehco-template.service
      when: update_ehco is not defined or not update_ehco
      stat:
        path: /usr/lib/systemd/system/ehco-template.service
      register: ehco_template_service
    - fail:
      when: not ehco_template_service.stat.exists

    - name: Get ehco version
      shell: /usr/local/bin/ehco -v
      register: ehco
    - name: Set fact for ehco version
      set_fact:
        ehco: "{{ ehco.stdout }}"
        cacheable: yes
  rescue:
    - name: Set ehco not exist
      set_fact:
        ehco: ""
        cacheable: yes
