---
- name: prepare ehco service
  when: update_status
  block:
    - name: Copy ehco service
      copy:
        src: /usr/lib/systemd/system/ehco-template.service
        dest: /usr/lib/systemd/system/ehco-{{ local_port }}.service
        owner: root
        group: root
        remote_src: yes
        follow: yes
    - name: Modify ehco service
      lineinfile:
        path: /usr/lib/systemd/system/ehco-{{ local_port }}.service
        regex: ^ExecStart
        line: ExecStart=/usr/local/bin/ehco {{ ehco_args }}

- name: enable or disable ehco
  systemd:
    name: ehco-{{ local_port }}
    state: "{{ 'restarted' if update_status else 'stopped' }}"
    enabled: "{{ 'yes' if update_status else 'no' }}"
    daemon_reload: yes

- name: check ehco service
  when: update_status
  block:
    - name: Get systemd status
      command: systemctl status ehco-{{ local_port }}
      register: systemd_status
      failed_when: "'Active: active' not in systemd_status.stdout"
  rescue:
    - name: Set ehco not exist
      when: "'/usr/local/bin/ehco: No such file or directory' in systemd_status.stdout"
      set_fact:
        gost: ""
        cacheable: yes
    - name: Set error
      set_fact:
        error: "{{ systemd_status.stdout }}"
        cacheable: yes
    - name: Fail
      fail: