---
- name: Check socat exist
  block:
    - name: Get socat version
      shell: socat -V
      register: socat
    - name: Set fact for socat version
      set_fact:
        socat: "{{ socat.stdout }}"
        cacheable: yes
  rescue:
    - name: Set socat not exist
      set_fact:
        socat: ""
        cacheable: yes
