[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles==23.1.0",
    "alembic==1.4.3",
    "ansible==2.10.1",
    "ansible-runner==1.4.6",
    "asyncpg>=0.30.0",
    "authlib==0.14.3",
    "bcrypt==3.2.0",
    "dnspython==2.1.0",
    "fabric==3.2.2",
    "fastapi==0.115.12",
    "fastapi-pagination[sqlalchemy]==0.12.34",
    "httpx==0.15.5",
    "huey==2.4.2",
    "jinja2==3.0.3",
    "loguru==0.7.2",
    "passlib==1.7.4",
    "psutil==5.7.2",
    "psycopg2-binary>=2.9.10",
    "pyjwt==1.7.1",
    "pytest==6.1.0",
    "python-multipart==0.0.5",
    "redis==5.0.0",
    "requests",
    "sentry-sdk>=2",
    "sqlalchemy==1.4.46",
    "sqlalchemy-utils==0.38.2",
    "sse-starlette==1.3.3",
    "strawberry-graphql[fastapi]>=0.219.1",
    "uvicorn[standard]>=0.34.0",
    "websockets==10.4",
    "orjson>=3.10,<4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
