---
- hosts: "{{ host | default('web') }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: brook setup
      when: update_brook is defined and update_brook
      block:
        - setup:
        - name: sync brook
          include_role:
            name: brook_sync
        - name: get brook version
          include_role:
            name: brook_get
  roles:
    - traffic_delete_monitor
    - brook