---
- hosts: "{{ host | default('web') }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: ehco setup
      when: update_ehco is defined and update_ehco
      block:
        - setup:
        - name: sync ehco
          include_role:
            name: ehco_sync
        - name: get ehco version
          include_role:
            name: ehco_get
  roles:
    - traffic_delete_monitor
    - ehco