---
- name: Download latest shadowsocks
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: shadowsocks setup
      when: update_shadowsocks is defined and update_shadowsocks
      block:
        - setup:
        - name: download shadowsocks
          include_role:
            name: shadowsocks_download

- hosts: "{{ host | default('web') }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: shadowsocks setup
      when: update_shadowsocks is defined and update_shadowsocks
      block:
        - setup:
        - name: sync shadowsocks
          include_role:
            name: shadowsocks_sync
        - name: get shadowsocks version
          include_role:
            name: shadowsocks_get
  roles:
    - traffic_delete_monitor
    - shadowsocks