---
- hosts: "{{ host | default('web') }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: shadowsocks setup
      when: update_shadowsocks is defined and update_shadowsocks
      block:
        - setup:
        - name: sync shadowsocks
          include_role:
            name: shadowsocks_sync
        - name: get shadowsocks version
          include_role:
            name: shadowsocks_get
  roles:
    - traffic_delete_monitor
    - shadowsocks