---
- hosts: "{{ host | default('web') }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: socat setup
      when: update_socat is defined and update_socat
      block:
        - setup:
        - name: Install/Update socat
          include_role:
            name: socat_update
        - name: sync socat
          include_role:
            name: socat_sync
        - name: get socat version
          include_role:
            name: socat_get
  roles:
    - traffic_delete_monitor
    - socat