---
- hosts: "{{ host | default('web') }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: v2ray setup
      when: update_v2ray is defined and update_v2ray
      block:
        - name: sync v2ray
          include_role:
            name: v2ray_sync
        - name: get v2ray version
          include_role:
            name: v2ray_get
  tasks:
    - setup:
  roles:
    - v2ray