---
- name: Check v2ray core exist
  block:
    - name: Get xray version
      shell: "{{ app_path }}xray -version"
    - name: Check v2ctl exist
      shell: "{{ app_path }}v2ctl uuid"
    - name: Get v2ray version
      shell: "{{ app_path }}v2ray -version"
      register: v2ray
    - name: Set fact for v2ray version
      set_fact:
        v2ray: "{{ v2ray.stdout }}"
        cacheable: yes
  rescue:
    - name: Set v2ray not exist
      set_fact:
        v2ray: ""
        cacheable: yes
