---
- name: Check iptables exist
  block:
    - name: Get iptables version
      shell: iptables -V
      register: iptables
    - name: Set fact for iptables version
      set_fact:
        iptables: "{{ iptables.stdout }}"
        cacheable: yes
  rescue:
    - name: Gather facts
      gather_facts:
        parallel: yes
    - name: Install iptables for centos
      when: ansible_facts.os_family == 'RedHat'
      yum:
        name: iptables
        state: present
    - name: Install iptables for debian/ubuntu
      when: ansible_facts.os_family == 'Debian'
      apt:
        name: iptables
        state: present
    - name: Get iptables version
      shell: iptables -V
      register: iptables
    - name: Set fact for iptables version
      set_fact:
        iptables: "{{ iptables.stdout }}"
        cacheable: yes
