---
- name: Exec app script
  when: update_status
  block:
    - name: Exec app script locally
      shell: /usr/local/bin/app.sh {{ local_port }} {{ remote_ip }}
      register: results
  rescue:
    - name: Sync app.sh
      copy:
        src: files/app.sh
        dest: /usr/local/bin/app.sh
        owner: root
        group: root
        mode: '0755'
    - name: Exec app script locally again
      shell: /usr/local/bin/app.sh {{ local_port }} {{ remote_ip }}
      register: traffic

- name: Set traffic result
  set_fact:
    traffic: "{{ traffic.stdout }}"
    cacheable: yes
  when: update_status

- name: Create v2ray config directory if it does not exist
  file:
    path: /usr/local/etc/v2ray
    state: directory
    mode: '0755'
  when: update_status

- name: Sync v2ray config
  copy:
    src: roles/v2ray/files/{{ port_id }}.json
    dest: /usr/local/etc/v2ray/{{ local_port }}.json
    owner: root
    group: root
  when: update_status

- name: enable & restart v2ray
  systemd:
    name: v2ray@{{ local_port }}
    state: "{{ 'restarted' if update_status else 'stopped' }}"
    enabled: "{{ 'yes' if update_status else 'no' }}"
    daemon_reload: yes
