---
- name: Get latest ehco download url
  shell: curl -Lso- https://api.github.com/repos/Ehco1996/ehco/releases/latest | python -m json.tool | grep -E "browser_download_url.*ehco.*linux_amd64" | awk '{print $2}' | xargs echo
  register: ehco_latest_download_url

- name: Remote old ehco binary
  file:
    path: roles/app/files/ehco
    state: absent

- name: Download latest ehco from Github
  get_url:
    url: "{{ ehco_latest_download_url.stdout }}"
    dest: roles/app/files/ehco
