---
- name: Sync ehco-template.service
  copy:
    src: files/ehco-template.service
    dest: /usr/lib/systemd/system/ehco-template.service
    owner: root
    group: root

- name: Sync ehco binary
  copy:
    src: roles/app/files/ehco
    dest: /usr/local/bin/ehco
    mode: +x
    owner: root
    group: root
