---
- name: Get architecture
  shell: uname -m
  register: arch
- name: Sync ehco binary for X64
  when: arch.stdout == 'x86_64'
  copy:
    src: files/ehco_1.1.1_linux_amd64
    dest: /usr/local/bin/ehco
    mode: +x
    owner: root
    group: root
- name: Sync ehco binary for ARM64
  when: arch.stdout == 'aarch64'
  copy:
    src: files/ehco_1.1.1_linux_arm64
    dest: /usr/local/bin/ehco
    mode: +x
    owner: root
    group: root
