---
- name: Check tiny_port_mapper exist
  block:
    - name: Get tiny_port_mapper version
      shell: tiny_port_mapper -h
      register: tiny_port_mapper
    - name: Set fact for tiny_port_mapper version
      set_fact:
        tiny_port_mapper: "{{ tiny_port_mapper.stdout }}"
        cacheable: yes
  rescue:
    - name: Set tiny_port_mapper not exist
      set_fact:
        tiny_port_mapper: ""
        cacheable: yes
