---
- name: Set iptables forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Exec iptables script
  script: roles/iptables/files/iptables.sh {{ iptables_args }}
  register: results

- name: Set fact for result
  set_fact:
    results: "{{ results.stdout }}"
    cacheable: yes