---
- name: Set iptables rule
  block:
    - name: Exec iptables script remotely to set forward rule
      script: files/iptables.sh {{ iptables_args }}
      args:
        executable: bash
      register: traffic
    - name: Set traffic result
      set_fact:
        traffic: "{{ traffic.stdout }}"
        cacheable: yes
    - name: Sync iptables.sh for updating SNAT
      copy:
        src: files/iptables.sh
        dest: /usr/local/bin/iptables.sh
        owner: root
        group: root
        mode: '0755'
