---
- name: prepare brook service
  when: update_status
  block:
    - name: Copy brook service
      copy:
        src: /usr/lib/systemd/system/brook-template.service
        dest: /usr/lib/systemd/system/brook-{{ local_port }}.service
        owner: root
        group: root
        remote_src: yes
        follow: yes
    - name: Modify brook service
      lineinfile:
        path: /usr/lib/systemd/system/brook-{{ local_port }}.service
        regex: ^ExecStart
        line: ExecStart=/usr/local/bin/brook {{ brook_args }}

- name: enable or disable brook
  systemd:
    name: brook-{{ local_port }}
    state: "{{ 'restarted' if update_status else 'stopped' }}"
    enabled: "{{ 'yes' if update_status else 'no' }}"
    daemon_reload: yes

- name: check brook service
  when: update_status
  block:
    - name: Get systemd status
      command: systemctl status brook-{{ local_port }}
      register: systemd_status
      failed_when: "'Active: active' not in systemd_status.stdout"
  rescue:
    - name: Set brook not exist
      when: "'/usr/local/bin/brook: No such file or directory' in systemd_status.stdout"
      set_fact:
        gost: ""
        cacheable: yes
    - name: Set error
      set_fact:
        error: "{{ systemd_status.stdout }}"
        cacheable: yes
    - name: Fail
      fail: