---
- name: get service facts
  service_facts:
  register: services

- name: Set iptables forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Sync gost.sh
  copy:
    src: files/gost.sh
    dest: /usr/local/bin/gost.sh
    owner: root
    group: root
    mode: '0755'

- name: Sync iptables.sh
  copy:
    src: files/iptables.sh
    dest: /usr/local/bin/iptables.sh
    owner: root
    group: root
    mode: '0755'

- name: Sync tc.sh
  copy:
    src: files/tc.sh
    dest: /usr/local/bin/tc.sh
    owner: root
    group: root
    mode: '0755'

- name: Sync get_traffic.sh
  copy:
    src: files/get_traffic.sh
    dest: /usr/local/bin/get_traffic.sh
    owner: root
    group: root
    mode: '0755'

- name: Sync gost.service
  copy:
    src: files/gost@.service
    dest: /usr/lib/systemd/system/gost@.service
    owner: root
    group: root

- name: Sync iptables-restore.service for centos
  when: ansible_facts.distribution == 'CentOS'
  copy:
    src: files/iptables-restore-centos.service
    dest: /usr/lib/systemd/system/iptables-restore.service
    owner: root
    group: root

- name: Sync iptables-restore.service for debian/ubuntu
  when: ansible_facts.distribution != 'CentOS'
  copy:
    src: files/iptables-restore.service
    dest: /usr/lib/systemd/system/iptables-restore.service
    owner: root
    group: root

- name: Stop firewalld
  when: ansible_facts.services["firewalld.service"] is defined
  systemd:
    name: firewalld
    enabled: 'no'
    state: 'stopped'

- name: enables iptables-restore
  systemd:
    name: iptables-restore
    enabled: 'yes'
    daemon_reload: yes
