---
- name: assert gost.service exists
  stat:
    path: /usr/lib/systemd/system/gost.service
  register: gost_service

- name: fail if systemd config not exist
  fail:
    msg: "gost.service not exists"
  when: gost_service.stat.islnk is not defined

- name: Ensure gost config dir exists
  file:
    path: /usr/local/etc/gost
    state: directory

- name: Sync gost config
  copy:
    src: roles/gost/files/config.json
    dest: /usr/local/etc/gost/config.json
    owner: root
    group: root

- name: enable & restart gost
  systemd:
    name: gost
    state: restarted
    enabled: yes
    daemon_reload: yes
