---
- name: Exec gost script
  when: update_status
  block:
    - name: Exec gost script locally
      shell: /usr/local/bin/gost.sh {{ local_port }} {{ remote_ip }}
      register: results
  rescue:
    - name: Sync gost.sh
      copy:
        src: files/gost.sh
        dest: /usr/local/bin/gost.sh
        owner: root
        group: root
        mode: '0755'
    - name: Exec gost script locally again
      shell: /usr/local/bin/gost.sh {{ local_port }} {{ remote_ip }}
      register: results

- name: Set fact for result
  set_fact:
    results: "{{ results.stdout }}"
    cacheable: yes
  when: update_status

- name: Sync gost config
  copy:
    src: roles/gost/files/{{ port_id }}.json
    dest: /usr/local/etc/gost/{{ local_port }}.json
    owner: root
    group: root
  when: update_status

- name: enable & restart gost
  systemd:
    name: gost@{{ local_port }}
    state: "{{ 'restarted' if update_status else 'stopped' }}"
    enabled: "{{ 'yes' if update_status else 'no' }}"
    daemon_reload: yes
