---
- name: assert gost.service exists
  stat:
    path: /usr/lib/systemd/system/gost@.service
  register: gost_service

- name: fail if systemd config not exist
  fail:
    msg: "gost.service not exists"
  when: gost_service.stat.islnk is not defined

- name: Ensure gost config dir exists
  file:
    path: /usr/local/etc/gost
    state: directory

- name: Sync gost config
  copy:
    src: roles/gost/files/{{ local_port }}.json
    dest: /usr/local/etc/gost/{{ local_port }}.json
    owner: root
    group: root
  when: update_status

- name: enable & restart gost
  systemd:
    name: gost@{{ local_port }}
    state: "{{ 'restarted' if update_status else 'stopped' }}"
    enabled: "{{ 'yes' if update_status else 'no' }}"
    daemon_reload: yes
  notify: "gost config changed"
