---
- name: Gather facts
  gather_facts:
    parallel: yes

- name: Install socat for CentOS
  when: ansible_facts.os_family == 'RedHat'
  yum:
    name: socat
    state: latest
    update_cache: yes

- name: Install socat for Debian/Ubuntu
  when: ansible_facts.os_family == 'Debian'
  apt:
    name: socat
    state: latest
    update_cache: yes