---
- name: setting wstunnel service
  block:
    - name: Copy wstunnel service
      when: update_status
      copy:
        src: /usr/lib/systemd/system/wstunnel-template.service
        dest: /usr/lib/systemd/system/wstunnel-{{ local_port }}.service
        owner: root
        group: root
        remote_src: yes
        follow: yes
    - name: Modify wstunnel service
      when: update_status
      lineinfile:
        path: /usr/lib/systemd/system/wstunnel-{{ local_port }}.service
        regex: ^ExecStart
        line: ExecStart=/usr/local/bin/wstunnel {{ wstunnel_args }}

    - name: enable or disable wstunnel
      systemd:
        name: wstunnel-{{ local_port }}
        state: "{{ 'restarted' if update_status else 'stopped' }}"
        enabled: "{{ 'yes' if update_status else 'no' }}"
        daemon_reload: yes
        
    - name: Get systemd status
      when: update_status
      command: systemctl status wstunnel-{{ local_port }}
      register: systemd_status
      failed_when: "'Active: active' not in systemd_status.stdout"
  rescue:
    - name: Retry install wstunnel next time
      set_fact:
        wstunnel: ""
        cacheable: yes
    - name: Set error
      set_fact:
        error: "{{ ansible_failed_result.msg }}"
        cacheable: yes
    - name: Set systemd error
      when: systemd_status is defined
      set_fact:
        systemd_error: "{{ systemd_status.stdout }}"
        cacheable: yes
    - fail:
        msg: "{{ ansible_failed_result.msg }}"