"""Add ansible_name and ansible_port

Revision ID: 07d160e702e0
Revises: 4454edd980da
Create Date: 2020-10-28 02:57:54.063305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d160e702e0'
down_revision = '4454edd980da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ansible_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ansible_port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('ansible_port')
        batch_op.drop_column('ansible_name')

    # ### end Alembic commands ###
