"""Usage to port

Revision ID: 0840e155743c
Revises: e5871068c2ae
Create Date: 2020-11-17 03:54:32.941173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0840e155743c'
down_revision = 'e5871068c2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage', sa.Integer(), nullable=True))
    op.execute('UPDATE port set usage=0')
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.alter_column('usage', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_column('usage')

    # ### end Alembic commands ###
