"""Add iperf to method enum

Revision ID: 154b3bb64ffa
Revises: 339a5265a24e
Create Date: 2021-01-04 07:59:43.152809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154b3bb64ffa'
down_revision = '339a5265a24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE methodenum ADD VALUE IF NOT EXISTS 'IPERF'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
