"""Make config as mutable dict

Revision ID: 22d0767fc6ff
Revises: 9f2851c635ee
Create Date: 2020-11-02 04:55:40.384897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d0767fc6ff'
down_revision = '9f2851c635ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
