"""Add server system facts

Revision ID: 307413e8d2bb
Revises: fe1c7deaaef2
Create Date: 2025-08-26 21:55:28.385157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '307413e8d2bb'
down_revision = 'fe1c7deaaef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('mem_total', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('os_release', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('probe_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('root_total', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('swap_total', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('swap_total')
        batch_op.drop_column('root_total')
        batch_op.drop_column('probe_version')
        batch_op.drop_column('os_release')
        batch_op.drop_column('mem_total')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
