"""Unique constraint for port num

Revision ID: 38be664c28a5
Revises: fbf2bcfa3370
Create Date: 2020-11-15 19:43:08.289410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38be664c28a5'
down_revision = 'fbf2bcfa3370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_constraint('_port_num_server_uc', type_='unique')
        batch_op.create_unique_constraint('_port_num_server_uc', ['num', 'server_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_constraint('_port_num_server_uc', type_='unique')
        batch_op.create_unique_constraint('_port_num_server_uc', ['external_num', 'server_id'])

    # ### end Alembic commands ###
