"""Add ansible_host to Server

Revision ID: 4454edd980da
Revises: ab92c0d8fe74
Create Date: 2020-10-20 04:21:51.403254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4454edd980da'
down_revision = 'ab92c0d8fe74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ansible_host', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('ansible_host')

    # ### end Alembic commands ###
