"""Add server_metric, disk_usage and network_counter

Revision ID: 492e2ac71b0a
Revises: 307413e8d2bb
Create Date: 2025-08-28 13:42:00.617117

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "492e2ac71b0a"
down_revision = "307413e8d2bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disk_usage",
        sa.Column("time", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("mount", sa.String(), nullable=False),
        sa.Column("used_bytes", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "mount", "time"),
    )

    op.create_table(
        "network_counter",
        sa.Column("time", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("iface", sa.String(), nullable=False),
        sa.Column("rx_bytes_total", sa.BigInteger(), nullable=False),
        sa.Column("tx_bytes_total", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "iface", "time"),
    )

    op.create_table(
        "server_metric",
        sa.Column("time", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("cpu_util_pct", sa.Float(), nullable=False),
        sa.Column("load_1m", sa.Float(), nullable=False),
        sa.Column("load_5m", sa.Float(), nullable=False),
        sa.Column("load_15m", sa.Float(), nullable=False),
        sa.Column("mem_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("swap_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("fs_root_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mem_used_pct", sa.Float(), nullable=True),
        sa.Column("fs_root_used_pct", sa.Float(), nullable=True),
        sa.Column("swap_used_pct", sa.Float(), nullable=True),
        sa.Column("net_rx_bps", sa.Float(), nullable=True),
        sa.Column("net_tx_bps", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "time"),
    )


def downgrade():
    op.drop_table("server_metric")
    op.drop_table("network_counter")
    op.drop_table("disk_usage")
