"""add server usage

Revision ID: 50828d7f1468
Revises: ee7c03c63dfa
Create Date: 2023-11-02 20:56:51.990005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50828d7f1468'
down_revision = 'ee7c03c63dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('cpu', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('memory', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('disk', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('server_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_usage_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_usage_id'))

    op.drop_table('server_usage')
    # ### end Alembic commands ###
