"""Add download upload to ServerUser

Revision ID: 62954a4ead1a
Revises: 95b1a518c8bf
Create Date: 2020-12-02 19:04:27.617001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62954a4ead1a'
down_revision = '95b1a518c8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('upload', sa.BigInteger(), nullable=True))
    op.execute("UPDATE server_user SET download = 0")
    op.execute("UPDATE server_user SET upload = 0")
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.alter_column('download', existing_type=sa.BigInteger(), nullable=False)
        batch_op.alter_column('upload', existing_type=sa.BigInteger(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.drop_column('upload')
        batch_op.drop_column('download')

    # ### end Alembic commands ###
