"""Add v2ray to method enum

Revision ID: 6415692aeb39
Revises: e73e40a6bb64
Create Date: 2020-12-07 04:02:50.161607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6415692aeb39'
down_revision = 'e73e40a6bb64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE methodenum ADD VALUE 'V2RAY'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
