"""add server last connect column

Revision ID: 646d8e2f6f12
Revises: 50828d7f1468
Create Date: 2023-11-10 16:54:48.775505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '646d8e2f6f12'
down_revision = '50828d7f1468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_connect', postgresql.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('last_connect')

    # ### end Alembic commands ###
