"""Use timezone aware timestamp for file

Revision ID: 755615b034b5
Revises: 6eaba2b0745a
Create Date: 2025-09-04 11:08:31.502912

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import TIMESTAMP


# revision identifiers, used by Alembic.
revision = "755615b034b5"
down_revision = "6eaba2b0745a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_column("created_at")
        batch_op.drop_column("updated_at")
        batch_op.add_column(
            sa.Column("created_at", TIMESTAMP(timezone=True), nullable=False)
        )
        batch_op.add_column(
            sa.Column("updated_at", TIMESTAMP(timezone=True), nullable=False)
        )


def downgrade():
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_column("created_at")
        batch_op.drop_column("updated_at")
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
