"""Rename ansible related fields

Revision ID: 7d8ca5f66e5f
Revises: f582d7b0eb00
Create Date: 2022-08-31 04:21:12.930811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8ca5f66e5f'
down_revision = 'f582d7b0eb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))
        batch_op.create_unique_constraint('_server_host_port_uc', ['host', 'port'])

    op.execute("UPDATE server SET host = ansible_host")
    op.execute("UPDATE server SET port = ansible_port")
    op.execute("UPDATE server SET \"user\" = ansible_user")

    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_constraint('_server_ansible_host_ansible_port_uc', type_='unique')
        batch_op.drop_column('ansible_port')
        batch_op.drop_column('ansible_user')
        batch_op.drop_column('ansible_host')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ansible_host', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ansible_user', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ansible_port', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('_server_ansible_host_ansible_port_uc', ['ansible_host', 'ansible_port'])

    op.execute("UPDATE server SET ansible_host = host, ansible_port = port, ansible_user = user")

    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_constraint('_server_host_port_uc', type_='unique')
        batch_op.drop_column('user')
        batch_op.drop_column('port')
        batch_op.drop_column('host')

    # ### end Alembic commands ###
