"""Add server_metric, disk_usage and network_counter

Revision ID: 82e1de08b245
Revises: 307413e8d2bb
Create Date: 2025-08-26 23:24:29.451909

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "82e1de08b245"
down_revision = "307413e8d2bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disk_usage",
        sa.Column("time", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("mount", sa.String(), nullable=False),
        sa.Column("used_bytes", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "time"),
    )
    with op.batch_alter_table("disk_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_disk_usage_mount"), ["mount"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_disk_usage_server_id"), ["server_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_disk_usage_time"), ["time"], unique=False)

    op.create_table(
        "network_counter",
        sa.Column("time", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("iface", sa.String(), nullable=False),
        sa.Column("rx_bytes_total", sa.BigInteger(), nullable=False),
        sa.Column("tx_bytes_total", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "time", "iface"),
    )
    with op.batch_alter_table("network_counter", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_network_counter_iface"), ["iface"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_network_counter_server_id"), ["server_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_network_counter_time"), ["time"], unique=False
        )

    op.create_table(
        "server_metric",
        sa.Column("time", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("cpu_util_pct", sa.Float(), nullable=False),
        sa.Column("load_1m", sa.Float(), nullable=False),
        sa.Column("load_5m", sa.Float(), nullable=False),
        sa.Column("load_15m", sa.Float(), nullable=False),
        sa.Column("mem_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("swap_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("fs_root_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mem_used_pct", sa.Float(), nullable=True),
        sa.Column("fs_root_used_pct", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "time"),
    )
    with op.batch_alter_table("server_metric", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_server_metric_server_id"), ["server_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_server_metric_time"), ["time"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()

    # Drop indexes with IF EXISTS
    conn.execute(text("DROP INDEX IF EXISTS ix_server_metric_time"))
    conn.execute(text("DROP INDEX IF EXISTS ix_server_metric_server_id"))
    conn.execute(text("DROP INDEX IF EXISTS ix_network_counter_time"))
    conn.execute(text("DROP INDEX IF EXISTS ix_network_counter_server_id"))
    conn.execute(text("DROP INDEX IF EXISTS ix_network_counter_iface"))
    conn.execute(text("DROP INDEX IF EXISTS ix_disk_usage_time"))
    conn.execute(text("DROP INDEX IF EXISTS ix_disk_usage_server_id"))
    conn.execute(text("DROP INDEX IF EXISTS ix_disk_usage_mount"))

    # Drop tables with IF EXISTS
    conn.execute(text("DROP TABLE IF EXISTS server_metric CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS network_counter CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS disk_usage CASCADE"))
