"""drop keyfile_name

Revision ID: 85584785e660
Revises: 44f1d8f3ef99
Create Date: 2023-04-02 10:47:20.513468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85584785e660'
down_revision = '44f1d8f3ef99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'file', ['key_file_id'], ['id'])
        batch_op.drop_column('key_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('key_file_id')

    # ### end Alembic commands ###
