"""initial schema

Revision ID: 95b1a518c8bf
Revises: 
Create Date: 2020-11-17 19:21:04.139763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b1a518c8bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('ansible_name', sa.String(), nullable=False),
    sa.Column('ansible_host', sa.String(), nullable=True),
    sa.Column('ansible_port', sa.Integer(), nullable=True),
    sa.Column('ansible_user', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('ssh_password', sa.String(), nullable=True),
    sa.Column('sudo_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ansible_host', 'ansible_port', name='_server_ansible_host_ansible_port_uc'),
    sa.UniqueConstraint('ansible_name', name='_server_ansible_name_uc')
    )
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_server_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_ops', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_num', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_num', 'server_id', name='_port_external_num_server_uc'),
    sa.UniqueConstraint('num', 'server_id', name='_port_num_server_uc')
    )
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_id'), ['id'], unique=False)

    op.create_table('server_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'user_id', name='_server_user_server_id_user_id_uc')
    )
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_user_id'), ['id'], unique=False)

    op.create_table('port_forward_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('method', sa.Enum('IPTABLES', 'GOST', name='methodenum'), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('port_forward_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_forward_rule_id'), ['id'], unique=False)

    op.create_table('port_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('download', sa.BigInteger(), nullable=False),
    sa.Column('upload', sa.BigInteger(), nullable=False),
    sa.Column('download_accumulate', sa.BigInteger(), nullable=False),
    sa.Column('upload_accumulate', sa.BigInteger(), nullable=False),
    sa.Column('download_checkpoint', sa.BigInteger(), nullable=False),
    sa.Column('upload_checkpoint', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id', name='_port_usage_port_id_uc')
    )
    with op.batch_alter_table('port_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_usage_id'), ['id'], unique=False)

    op.create_table('port_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id', 'user_id', name='_port_user_server_id_user_id_uc')
    )
    with op.batch_alter_table('port_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_user_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_user_id'))

    op.drop_table('port_user')
    with op.batch_alter_table('port_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_usage_id'))

    op.drop_table('port_usage')
    with op.batch_alter_table('port_forward_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_forward_rule_id'))

    op.drop_table('port_forward_rule')
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_user_id'))

    op.drop_table('server_user')
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_id'))

    op.drop_table('port')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_name'))
        batch_op.drop_index(batch_op.f('ix_server_id'))

    op.drop_table('server')
    # ### end Alembic commands ###
