"""Make num nullable and rename

Revision ID: 9c6d3b3db70f
Revises: 8e6bb7e17cc0
Create Date: 2020-11-07 05:51:16.917316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6d3b3db70f'
down_revision = '8e6bb7e17cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.alter_column('internal_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('num',
               existing_type=sa.INTEGER(),
               new_column_name='external_num',
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.alter_column('num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('internal_num',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
