"""MRename internal_num to num

Revision ID: a40cf97c7b28
Revises: 9c6d3b3db70f
Create Date: 2020-11-07 07:24:56.616940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40cf97c7b28'
down_revision = '9c6d3b3db70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.alter_column('internal_num',
               existing_type=sa.INTEGER(),
               new_column_name='num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.alter_column('num',
               existing_type=sa.INTEGER(),
               new_column_name='internal_num')

    # ### end Alembic commands ###
