"""Change config to JSON

Revision ID: a7c0a10ba304
Revises: 07bedcd739a9
Create Date: 2020-11-02 05:42:19.202013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c0a10ba304'
down_revision = '07bedcd739a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
