"""Add remote_ip and status to PortForwardRule

Revision ID: ab92c0d8fe74
Revises: 0190a3f46a65
Create Date: 2020-10-20 04:04:21.770944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab92c0d8fe74'
down_revision = '0190a3f46a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_forward_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_ip', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('port_user', schema=None) as batch_op:
        batch_op.create_unique_constraint('_server_user_server_id_user_id_uc', ['port_id', 'user_id'])

    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.create_unique_constraint('_server_user_server_id_user_id_uc', ['server_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.drop_constraint('_server_user_server_id_user_id_uc', type_='unique')

    with op.batch_alter_table('port_user', schema=None) as batch_op:
        batch_op.drop_constraint('_server_user_server_id_user_id_uc', type_='unique')

    with op.batch_alter_table('port_forward_rule', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('remote_ip')

    # ### end Alembic commands ###
