"""Add brook to method enum

Revision ID: b0253cae8057
Revises: 6415692aeb39
Create Date: 2020-12-09 23:25:55.156260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0253cae8057'
down_revision = '6415692aeb39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE methodenum ADD VALUE 'BROOK'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
