"""Add socat to method enum

Revision ID: b926f48a103f
Revises: b0253cae8057
Create Date: 2020-12-11 08:08:05.086705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b926f48a103f'
down_revision = 'b0253cae8057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE methodenum ADD VALUE 'SOCAT'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
