"""Add config to server and port

Revision ID: c7c595f34a99
Revises: a40cf97c7b28
Create Date: 2020-11-13 20:06:23.235604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision = 'c7c595f34a99'
down_revision = 'a40cf97c7b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))
    op.execute('UPDATE port set config="{}"')
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.alter_column('config', existing_type=sqlite.JSON(), nullable=False)

    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))
    op.execute('UPDATE server set config="{}"')
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.alter_column('config', existing_type=sqlite.JSON(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('config')

    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###
