"""Add node_exporter to method enum

Revision ID: cbab2061efb1
Revises: b926f48a103f
Create Date: 2020-12-11 22:31:45.384754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbab2061efb1'
down_revision = 'b926f48a103f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE methodenum ADD VALUE 'NODE_EXPORTER'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
