"""Add unqiue constraint to external_num and server_id

Revision ID: e5871068c2ae
Revises: 79737414cefc
Create Date: 2020-11-16 21:52:33.085786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5871068c2ae'
down_revision = '79737414cefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.create_unique_constraint('_port_external_num_server_uc', ['external_num', 'server_id'])
        batch_op.drop_constraint('_port_num_server_uc', type_='unique')
        batch_op.create_unique_constraint('_port_num_server_uc', ['num', 'server_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_constraint('_port_num_server_uc', type_='unique')
        batch_op.create_unique_constraint('_port_num_server_uc', ['external_num', 'server_id'])
        batch_op.drop_constraint('_port_external_num_server_uc', type_='unique')

    # ### end Alembic commands ###
