"""Add notes to Port and Server

Revision ID: e73e40a6bb64
Revises: 62954a4ead1a
Create Date: 2020-12-03 07:40:55.366269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73e40a6bb64'
down_revision = '62954a4ead1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
