"""Drop ansible_name

Revision ID: f582d7b0eb00
Revises: ea4a5dba09c3
Create Date: 2022-08-31 04:14:50.477194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f582d7b0eb00'
down_revision = 'ea4a5dba09c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('ansible_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ansible_name', sa.Text(), nullable=True))
    op.execute("UPDATE server SET ansible_name = name")
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.alter_column('ansible_name', existing_type=sa.Text(), nullable=False)
    # ### end Alembic commands ###
