"""Add config to server_user and port_user

Revision ID: fbf2bcfa3370
Revises: c7c595f34a99
Create Date: 2020-11-13 23:12:47.674177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fbf2bcfa3370'
down_revision = 'c7c595f34a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('port_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))
    op.execute('UPDATE port_user set config="{}"')
    with op.batch_alter_table('port_user', schema=None) as batch_op:
        batch_op.alter_column('config', existing_type=sqlite.JSON(), nullable=False)

    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))
    op.execute('UPDATE server_user set config="{}"')
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.alter_column('config', existing_type=sqlite.JSON(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_user', schema=None) as batch_op:
        batch_op.drop_column('config')

    with op.batch_alter_table('port_user', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###
