---
- name: Get architecture
  shell: uname -m
  register: arch
- name: Check shadowsocks exist
  block:
    - name: Get shadowsocks_go version
      shell: shadowsocks_go -version
    - name: Get shadowsocks_go2 version
      shell: shadowsocks_go2 version
      register: shadowsocks
    - name: Set fact for shadowsocks version
      set_fact:
        shadowsocks: "{{ shadowsocks.stdout }}"
        cacheable: yes
  rescue:
    - name: Set shadowsocks not exist
      set_fact:
        shadowsocks: ""
        cacheable: yes
