---
- name: Check shadowsocks exist
  block:
    - name: Get shadowsocks version
      shell: shadowsocks_go -version
      register: shadowsocks
    - name: Set fact for shadowsocks version
      set_fact:
        shadowsocks: "{{ shadowsocks.stdout }}"
        cacheable: yes
  rescue:
    - name: Set shadowsocks not exist
      set_fact:
        shadowsocks: ""
        cacheable: yes
