---
- name: Check wstunnel exist
  block:
    - name: Get wstunnel version
      shell: wstunnel -V
      register: wstunnel
    - name: Set fact for wstunnel version
      set_fact:
        wstunnel: "{{ wstunnel.stdout }}"
        cacheable: yes
  rescue:
    - name: Set wstunnel not exist
      set_fact:
        wstunnel: ""
        cacheable: yes
