---
- name: Sync tiny_port_mapper-template.service
  copy:
    src: files/tiny_port_mapper-template.service
    dest: /usr/lib/systemd/system/tiny_port_mapper-template.service
    owner: root
    group: root

- name: Sync tiny_port_mapper binary
  copy:
    src: files/tinymapper_amd64_20200818.0
    dest: /usr/local/bin/tiny_port_mapper
    mode: +x
    owner: root
    group: root
