---
- name: "Check {{ app_name }} exist"
  block:
    - name: "Get {{ app_name }} version"
      shell: "{{ app_name }} {{ app_version_arg }}"
      register: app_version
    - name: "Set fact for {{ app_name }} version"
      set_fact: { "{{ app_name }}": "{{ app_version.stdout }}", "cacheable": yes }
  rescue:
    - name: "Set {{ app_name }} not exist"
      set_fact: { "{{ app_name }}": "", "cacheable": yes }
