---
- name: Get and monitor port {{ local_port }} traffic for app
  when: update_status is defined and update_status
  block:
    - name: Exec iptables script remotely to get and monitor app traffic
      script: files/iptables.sh monitor {{ local_port }} {{ remote_ip }}
      args:
        executable: bash
      register: traffic
    - name: Set traffic result
      set_fact:
        traffic: "{{ traffic.stdout }}"
        cacheable: yes
