---
- name: Delete old monitor rule
  shell: iptables -S | grep '{{ local_port }}->' | awk '{$1="";$COMMEND="iptables -D "$0; system($COMMEND)}'
  listen: "gost config changed"
  when: remote_ip == ""

- name: Get interfaces
  shell: ip route show | grep default | awk '{print $5}'
  register: iface
  listen: "gost config changed"
  when: remote_ip != ""

- name: Get inet
  shell: ip address show {{ iface.stdout }} scope global |  awk '/inet / {split($2,var,"/"); print var[1]}'
  register: inet
  listen: "gost config changed"
  when: remote_ip != ""

- name: Adjust download iptables rule
  iptables:
    action: append
    state: "{{ 'present' if update_status else 'absent' }}"
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    source: "{{ remote_ip }}"
    comment: "DOWNLOAD {{ local_port }}->{{ remote_ip }}"
  listen: "gost config changed"
  when: remote_ip != ""

- name: Adjust upload iptables rule
  iptables:
    action: append
    state: "{{ 'present' if update_status else 'absent' }}"
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination: "{{ inet.stdout }}"
    destination_port: "{{ local_port }}"
    comment: "UPLOAD {{ local_port }}->{{ remote_ip }}"
  listen: "gost config changed"
  when: remote_ip != ""