---
- name: Get latest wstunnel download url
  shell: curl -Lso- https://api.github.com/repos/erebe/wstunnel/releases/latest | grep -E "browser_download_url.*wstunnel.*x64-linux" | awk '{print $2}' | xargs echo
  register: wstunnel_latest_download_url

- name: Remote old wstunnel binary
  file:
    path: roles/wstunnel/files/wstunnel
    state: absent

- name: Download latest wstunnel from Github
  get_url:
    url: "{{ wstunnel_latest_download_url.stdout }}"
    dest: roles/wstunnel/files/wstunnel.zip

- name: Unzip wstunnel.zip
  shell: unzip -u -d roles/wstunnel/files/ roles/wstunnel/files/wstunnel.zip 