---
- name: Enable BBR fq
  sysctl:
    name: net.core.default_qdisc
    value: fq
    sysctl_set: yes
    state: present
    reload: yes

- name: Enable BBR bbr
  sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
    sysctl_set: yes
    state: present
    reload: yes
