---
- name: Sync traffics and rules for all ports
  block:
    - name: Exec iptables script remotely to list all traffics
      script: files/iptables.sh list_all
      args:
        executable: bash
      register: traffic
    - name: Set traffic result
      set_fact:
        traffic: "{{ traffic.stdout }}"
        cacheable: yes
    - name: Exec iptables script remotely to list all rules
      script: files/iptables.sh list_rules
      args:
        executable: bash
      register: rules
    - name: Set rule result
      set_fact:
        rules: "{{ rules.stdout }}"
        cacheable: yes
