---
- name: Sync shadowsocks_go binary
  copy:
    src: files/shadowsocks-server-1.2.1
    dest: /usr/local/bin/shadowsocks_go
    mode: +x
    owner: root
    group: root
- name: Sync shadowsocks_go2 binary
  copy:
    src: files/shadowsocks2-linux-v0.1.5
    dest: /usr/local/bin/shadowsocks_go2
    mode: +x
    owner: root
    group: root