---
- name: Setting tiny_port_mapper service
  block:
    - name: Copy tiny_port_mapper service
      when: update_status
      copy:
        src: /usr/lib/systemd/system/tiny_port_mapper-template.service
        dest: /usr/lib/systemd/system/tiny_port_mapper-{{ local_port }}.service
        owner: root
        group: root
        remote_src: yes
        follow: yes
    - name: Modify tiny_port_mapper service
      when: update_status
      lineinfile:
        path: /usr/lib/systemd/system/tiny_port_mapper-{{ local_port }}.service
        regex: ^ExecStart
        line: ExecStart=/usr/local/bin/tiny_port_mapper {{ tiny_port_mapper_args }}

    - name: enable or disable tiny_port_mapper
      systemd:
        name: tiny_port_mapper-{{ local_port }}
        state: "{{ 'restarted' if update_status else 'stopped' }}"
        enabled: "{{ 'yes' if update_status else 'no' }}"
        daemon_reload: yes

    - name: Get systemd status
      when: update_status
      command: systemctl status tiny_port_mapper-{{ local_port }}
      register: systemd_status
      failed_when: "'Active: active' not in systemd_status.stdout"
  rescue:
    - name: Retry install tiny_port_mapper next time
      set_fact:
        tiny_port_mapper: ""
        cacheable: yes
    - name: Set error
      set_fact:
        error: "{{ ansible_failed_result.msg }}"
        cacheable: yes
    - name: Set systemd error
      when: systemd_status is defined
      set_fact:
        systemd_error: "{{ systemd_status.stdout }}"
        cacheable: yes
    - fail:
        msg: "{{ ansible_failed_result.msg }}"