---
- name: prepare tiny_port_mapper service
  when: update_status
  block:
    - name: Copy tiny_port_mapper service
      copy:
        src: /usr/lib/systemd/system/tiny_port_mapper-template.service
        dest: /usr/lib/systemd/system/tiny_port_mapper-{{ local_port }}.service
        owner: root
        group: root
        remote_src: yes
        follow: yes
    - name: Modify tiny_port_mapper service
      lineinfile:
        path: /usr/lib/systemd/system/tiny_port_mapper-{{ local_port }}.service
        regex: ^ExecStart
        line: ExecStart=/usr/local/bin/tiny_port_mapper {{ tiny_port_mapper_args }}

- name: enable or disable tiny_port_mapper
  systemd:
    name: tiny_port_mapper-{{ local_port }}
    state: "{{ 'restarted' if update_status else 'stopped' }}"
    enabled: "{{ 'yes' if update_status else 'no' }}"
    daemon_reload: yes

- name: check tiny_port_mapper service
  when: update_status
  block:
    - name: Get systemd status
      command: systemctl status tiny_port_mapper-{{ local_port }}
      register: systemd_status
      failed_when: "'Active: active' not in systemd_status.stdout"
  rescue:
    - name: Set tiny_port_mapper not exist
      when: "'/usr/local/bin/tiny_port_mapper: No such file or directory' in systemd_status.stdout"
      set_fact:
        gost: ""
        cacheable: yes
    - name: Set error
      set_fact:
        error: "{{ systemd_status.stdout }}"
        cacheable: yes
    - name: Fail
      fail: