---
- name: Get latest brook download url
  shell: curl -Lso- https://api.github.com/repos/txthinking/brook/releases/latest | grep -E "browser_download_url.*brook_linux_amd64" | awk '{print $2}' | xargs echo
  register: brook_latest_download_url

- name: Remote old brook binary
  file:
    path: roles/brook/files/brook
    state: absent

- name: Download latest brook from Github
  get_url:
    url: "{{ brook_latest_download_url.stdout }}"
    dest: roles/brook/files/brook
