---
- name: Gather facts
  gather_facts:
    parallel: yes

- name: Install iperf3 for CentOS
  when: ansible_facts.os_family == 'RedHat'
  yum:
    name: iperf3
    state: present

- name: Install iperf3 for Debian/Ubuntu
  when: ansible_facts.os_family == 'Debian'
  apt:
    name: iperf3
    state: present
