---
- name: Gather facts
  gather_facts:
    parallel: yes

- name: Install iperf3 for CentOS
  when: ansible_facts.os_family == 'RedHat'
  block:
    - name: install iperf3 for CentOS
      yum:
        name: https://iperf.fr/download/fedora/iperf3-3.1.3-1.fc24.x86_64.rpm
        state: present

- name: Install socat for Debian/Ubuntu
  when: ansible_facts.os_family == 'Debian'
  block:
    - name: remove old install
      apt:
        name:
          - iperf3
          - libiperf0
        state: absent
    - name: install iperf3 dependency
      apt:
        name: libsctp1
        state: latest
        update_cache: yes
    - name: install libiperf0
      apt:
        deb: https://iperf.fr/download/ubuntu/libiperf0_3.7-3_amd64.deb
    - name: install iperf3
      apt:
        deb: https://iperf.fr/download/ubuntu/iperf3_3.7-3_amd64.deb
