---
- name: Sync iptables.sh
  copy:
    src: files/iptables.sh
    dest: /usr/local/bin/iptables.sh
    owner: root
    group: root
    mode: '0755'

- name: Sync tc.sh
  copy:
    src: files/tc.sh
    dest: /usr/local/bin/tc.sh
    owner: root
    group: root
    mode: '0755'
